sudo: required

language: minimal

services:
  - docker

script:
  - docker build -t "$TRAVIS_REPO_SLUG" .

before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

deploy:
  - provider: script
    script: docker push "$TRAVIS_REPO_SLUG"
    skip_cleanup: true
    on:
      branch: master
