version: '3'
services:
  web:
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:jaspervanmerle.com,www.jaspervanmerle.com"
    restart: always
networks:
  web:
    external: true
