version: '3'
services:
  web:
    image: jmerle/personal-website
    networks:
      - web
    labels:
      traefik.enable: true
      traefik.frontend.rule: "Host:jaspervanmerle.com,www.jaspervanmerle.com,jaspervanmerle.nl,www.jaspervanmerle.nl,jmerle.me,www.jmerle.me,jmerle.dev,www.jmerle.dev"
      com.centurylinklabs.watchtower.enable: true
    restart: unless-stopped
networks:
  web:
    external: true
