name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure SSH key
        run: echo TODO

      - name: Push to Dokku
        run: echo TODO
