name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Dokku
        uses: vitalyliber/dokku-github-action@v4.0
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: jmerle.dev
          PROJECT: personal-website
