name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to Dokku
        uses: dokku/github-action@v1
        with:
          git_remote_url: ssh://dokku@jmerle.dev:22/personal-website
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
